# BORRA LO DE MYSQL
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# PON ESTO PARA POSTGRES
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# (Opcional) Esto ayuda a que Hibernate cree las tablas si no existen
spring.jpa.hibernate.ddl-auto=update